### ISSUE TITLE
Cross Origin Resource Sharing is blocked while running application on ubuntu os in digital ocean server

### ISSUE THREAD

**Issue by rbiswal1990** [HDI-Project/ATMSeer#28] opened 2019-06-18 08:46 UTC
Access to XMLHttpRequest at 'http://139.59.xx.xx:7777/api/new_datarun/85' from origin 'http://139.59.xx.xx:7779' has been blocked by CORS policy: **No 'Access-Control-Allow-Origin' header is present on the requested resource.**

The above error is coming after deploying application in digital ocean. Note: File upload is successful, but next requests are failing by CORS errors.

Any suggestion to resolve the issue is appreciated.
Thanks!

**Comment by micahjsmith** [comment] 2020-06-09 16:57
Dupe of #34

**Closed by micahjsmith** 2020-06-09 16:57 UTC
